### ISSUE TITLE
Webm output double the size of the canvas, p5.js

### ISSUE THREAD

**Issue by 5yF0Rc3** [spite/ccapture.js#116]
My canvas in p5.js is 700x700, but the output of the Webm is 1400x1400. Is this normal? Can or should I change the size somewhere?

**Comment by rdsilver** [comment]
That is not normal, there is probably an error in your code. 

You can see on 3dgifmaker.com, the webm download respects the size of canvas.

**Comment by spite** [comment]
If you have a 700x700 canvas with a devicePixelRatio of 2, the canvas will probably be 1400x1400. That could be one reason.

**Comment by rdsilver** [comment]
@spite That's a good point, you can set p5.js to p5.pixelDensity(1) to potentially fix it 5yF0R

**Comment by 5yF0Rc3** [comment]
I haven't worked on that project for a while and it seems it resolved itself. However, with pixelDensity(2) the output of Webm would really be 2 times the size.
