### ISSUE TITLE
Uncaught Frame 2 has a different width

### ISSUE THREAD

**Issue by sipsipsip** [spite/ccapture.js#12]
When adding width and height property to <canvas> then I can't download the video, it returns "uncaught Frame 2 has a different width"

**Comment by spite** [comment]
If you change the size of the canvas at some point (by code, by opening DevTools and the canvas has 100% width, etc) the frames will have different dimensions and Whammy.js won't be able to encode the video. 

Or may be you've pushed the first frame before actually resizing the canvas, and then the second pushed frame has the correct size, but it's already wrong from Whammy's perspective. Could this be the situation?

**Comment by sipsipsip** [comment]
Actually, I changed the width using percentage value. Literally I don't do anything with the windows, but I think you're right, the canvas change slightly without being detected by my bare eyes.

The solution was setting a fixed width and height value. Thanks for the fast response. This tool is great!

**Comment by zdenham** [comment]
Running into the same issue with fixed width and height attributes. I'm running a vertex shader that distorts the video, when there is no distortion the video exports fine, when distorted, however, I get the above error. Is it possible to change the canvas dimensions inadvertently from the shader?
