### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toDataURL' of null

### ISSUE THREAD

**Issue by sipsipsip** [spite/ccapture.js#13]
Happens, when I use with TweenJS.

**Comment by sipsipsip** [comment]
Also this error when I tried to download the animation resulted from tweenjs 


CCapture.all.min.js:12 Uncaught InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by spite** [comment]
What browser and platform are you using (version and all)?

**Comment by sipsipsip** [comment]
Chrome, latest version (49.xx), Mac OSX, El Capitan. I guess it's related to TweenJS, previously I combine with PaperJS, it works fine, with GSAP works but the animation doesn't run smoothly. When I use tweenjs, I got this problem

**Comment by spite** [comment]
I would need a test case online to debug the problem. If you're having issues with GSAP or other ways of animation, let me know and I'll debug them.

**Comment by sipsipsip** [comment]
Perhaps, this is related to the issue here http://stackoverflow.com/questions/22578530/failed-to-execute-atob-on-window

**Comment by sipsipsip** [comment]
![screen shot 2016-03-16 at 12 11 31](https://cloud.githubusercontent.com/assets/15917886/13802592/14e5b21a-eb70-11e5-89ec-293b1643bf7c.png)
I guess it has something todo with whammy
