### ISSUE TITLE
Several problems

### ISSUE THREAD

**Issue by Connum** [spite/ccapture.js#15]
Hi there,

First of all: great work! I have, howerver, some problems. I am using CCapture.all.min.js

First of all, even when setting the display option to false when constructing the capturer, the black box with red text is being displayed in the top left corner. How can I get rid of that?

The second issue is, that the framerate option also seems to be ignored. I set it to 3 or 1, but the frame counter in the top left quickly goes into the hundreds within a few seconds.

And thirdly: When I use gif as output format, the output is only in black and white. How can that happen and how do I get it to record colors? There also seems to be quite a performance issue with gif generation, although I'm only capturing a canvas of 500x500px in size.

Any help appreciated!

P.S.: The demo also seems to be broken for gif output. You get the following in the console:
"NetworkError: 404 Not Found - https://www.clicktorelease.com/src/gif.worker.js"

**Comment by spite** [comment]
Hi, @Connum. Let's go step by step:

- display: good catch, I've fixed it and it's updated on the repo

- framerate: that option defines the framerate of the output capture,  but the system will capture as fast as possible, until you call .stop() or the time limit set in timeLimit is reached. If you want to set a frame limit, you can take your framerate and calculate the time limit accordingly.

- gif: that's up to gif.js, but i haven't had that problem. if you can post the code somewhere it can be run, i can take a look. I've also fixed the web worker script include on the site. Thanks for catching that one, too!
