### ISSUE TITLE
alpha transparency

### ISSUE THREAD

**Issue by tonycaso** [spite/ccapture.js#18]
Thanks for this script, it's just what I needed.

I'm trying to save a transparent canvas to webm but I get a black background.
Is it possible to save a transparent background with webm?

Thanks

**Comment by aleen42** [comment]
I think we can just change this library.

**Comment by aleen42** [comment]
@tonycaso I have just overridden the function:

```js
function _capture(canvas) {
       if (_settings.format === 'webm') {
       		/** store current context state into a new canvas */
       		var c = document.createElement('canvas');
       		var ctx = c.getContext('2d');
			c.width  = canvas.width;
			c.height = canvas.height;
			ctx.fillStyle = _settings.bakckgroundColor;
			ctx.fillRect(0, 0, canvas.width, canvas.height);
			ctx.drawImage(canvas, 0, 0);
       	}

       	if (_capturing) {
       	       	if (_settings.motionBlurFrames > 2) {
       	       	       	_checkFrame(c);
       	       	       	_blendFrame(c);

       	       	       	if (_intermediateFrameCount >= .5 * _settings.motionBlurFrames) {
       	       	       	       	_saveFrame();
       	       	       	} else {
       	       	       	       	_step();
       	       	       	}
       	       	} else {
       	       	       	_encoder.add(c);
       	       	       	_frameCount++;
       	       	       	_log('Full Frame! ' + _frameCount);
       	       	}
       	}
}
```

And then you can just create a CCapture object `capturer` like the following:

```js
capturer = new CCapture({
	verbose: false, 
	display: false,
	framerate: drawFPS,
	format: 'webm',
	frameLimit: 0,
	bakckgroundColor: '#fff',
	onProcess: function (frameCount) {
	    time.mark('Capturing Frame Number: <span class="font-a10000 font-bold">' + frameCount + '</span>', 'frameCount');
	}
});	
```

**Comment by spite** [comment]
I think @tonycaso was asking for alpha support on webm (which doesn't support)

**Comment by aleen42** [comment]
@spite Oh, maybe, transparent pixel can be represented by a white value.

**Comment by spite** [comment]
Yes, it can be masked with any color (specially #00ff00 or #ff00ff), but the developer can implement that in his own code (adding a solid background color). Your fix is still god, though (except bakckgroundColor should be backgroundColor)

**Comment by aleen42** [comment]
@spite Yup, that's right. However, when we must layering in Canvas, that should be a complex problem if developer implement this in their code. Here is the example video of my application: http://share.soundtooth.cn/2d92cca5-c9b8-85ed-3492-436423a9005f.webm . When drawing the red color, it will be a problem for our developers.

**Comment by spite** [comment]
i would advice using the PNG option of the capturer and use FFmpeg to create a QuickTime or AVI video that supports transparency natively.
