### ISSUE TITLE
Is there a way to capture Plotly 3D graph using this library? 

### ISSUE THREAD

**Issue by Rudresh-Ajgaonkar** [spite/ccapture.js#22]
Sorry for opening an issue but i couldnt find any support on stack oveerflow

This is the codepen of what i have tried so far. I am not able to link the render function of plotly to the construct mentioned in the documentation. 

```
function render(){
    requestAnimationFrame(render);
    // rendering stuff ...
    capturer.capture( canvas );
}

render()
```

Need Some help

**Comment by spite** [comment]
Can you post some example code of what you want to capture?

**Comment by Rudresh-Ajgaonkar** [comment]
Thanks a lot for the reply. I had almost lost hope.

Here is the codepen: 

http://codepen.io/rudi8292/pen/wWxJmE

I am trying to capture a webm of the above plot. 
Just to try my luck , i tried to capture a png by fetching plotly dataURL and painting on the canvas and then capture using ccapture like following : 

```
$("#startRecording").click(function(){
  var myPlot = document.getElementById('myDiv');
  myPlot.on("plotly_relayout", function(data) {
    capturer.start();
    abc.then((gd) => {
      return Plotly.toImage(gd);
    }).then((dataURI) => {
      // console.log(dataURI);
      var canvas = document.createElement('canvas'),
          context = canvas.getContext('2d'),
          image = new Image();
      image.addEventListener('load', function() {
        canvas.width = image.width;
        canvas.height = image.height;
        context.drawImage(image, 0, 0, canvas.width, canvas.height);
        capturer.start();
        capturer.capture(canvas);
  });
      setTimeout(function () {
      }, 10);
});
});
});

```

My Goal is to take a video of the plot. 

Any help provided would be of great help!

**Comment by Rudresh-Ajgaonkar** [comment]
Hey sorry to bother, but did you get through any insights regarding the problem?

**Comment by spite** [comment]
Here's your example modified so it works: https://gist.github.com/spite/4041bd77993779ea8601fc8add961001

First, you were getting the wrong <canvas> element, thus passing a null reference to the library.
Second, plot.ly doesn't seem to support preserveDrawingBuffer, so you'll need the first block of script BEFORE anything else runs that modifies all <canvas> so they all have preserveDrawingBuffer. The alpha parameter you can choose what to do: if it's set to false, the graph will have black background, may be you can fix that with some plot.ly setting.

**Comment by Rudresh-Ajgaonkar** [comment]
Thanks for this fix
