### ISSUE TITLE
Error while recording as gif

### ISSUE THREAD

**Issue by srijackec** [spite/ccapture.js#26]
Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///C:/Users/Admin/Downloads/ccapture.js-master/ccapture.js-master/src/gif.worker.js' cannot be accessed from origin 'null'.

While running the example im getting above error. I tried with chrome and safari browser. No response.

**Comment by spite** [comment]
Try running from a web server instead of directly from file. I gather you're on Windows, give Fenix a try http://fenixwebserver.com/, it's very easy to use.
