### ISSUE TITLE
Frames captured against black background

### ISSUE THREAD

**Issue by nirali1** [spite/ccapture.js#27]
Hi
I am using tar.js to export  jpg images. But the background color of the images is black,
In my canvas, i have set the background color as white
What should i do to get the exported images with white background?

Thanks in advance

**Comment by spite** [comment]
Is the background color set explicitly to black in Canvas2D/WebGL, or are you rendering on a transparent canvas on top of a CSS black background? There's a difference, and CCapture can only get the right background color in the first option.

**Comment by nirali1** [comment]
I have set the background color explicitly to white in Canvas2D.

var canvas = document.querySelector('#myCanvas');
canvas.style.backgroundColor = 'rgba(255, 255, 255, 0.9)';

**Comment by spite** [comment]
As I said, CSS background can't be captured because it's outside of the canvas. The browser is composing a transparent canvas on top of an element with white color. Try using context.fillRect with white fillStyle color where -i imagine- you're using context.clearRect.

**Comment by nirali1** [comment]
Thanks. That worked.
