### ISSUE TITLE
Add missing download.js import

### ISSUE THREAD

**Issue by vorg** [spite/ccapture.js#29]
The correct way to import the lib in order for jpeg to work should be changed from:

```html
<script src="CCapture.min.js"></script>
<script src="tar.js"></script>
```

to:

```html
<script src="build/CCapture.min.js"></script>
<script src="src/tar.js"></script>
<script src="src/download.js"></script>
```

**Comment by spite** [comment]
Yes. CCapture.all.min.js has all the dependencies bundled, too.

**Comment by spite** [comment]
Fixed on https://github.com/spite/ccapture.js/commit/8dd62486f8798b3e147515b3e57c7859403bba08. The paths are left as they are, I think it's up to the user where they put their dependencies.
