### ISSUE TITLE
Gif is not animated

### ISSUE THREAD

**Issue by hugohil** [spite/ccapture.js#3]
Hi there !

I'm using your library with [seriouslyjs](https://github.com/brianchirls/Seriously.js) to convert the canvas animation into a gif.

I get no error while running my code, but when I open the `blob`, I just have the first frame (the one when I clicked the button), but no animation.

I made a [codepen](http://codepen.io/hugohil/pen/EjWXWb) to show you, but due to CORS policy you cannot run it directly. However, you can copy/paste the code there and download the videos to perform a quick test locally.

**Comment by spite** [comment]
Hi! I think you're getting one single frame because you're calling capturer.capture just once.

Capturer.capture is like .push() into an array: you have to call it every time you want a frame into the final exported file.

I hope that solves your problem.

**Comment by hugohil** [comment]
Yay! It works perfectly, thanks !
I should have thought of it though...

I still have trouble downloading the gif once it is processed. As you do in the basic example, I do the following:
```javascript
capturer.save(function (
  window.location = blob;
});
```

But the gif I get there is not a proper gif and when I try to download it, chrome tells me the file is empty.
![screen shot 2015-06-20 at 13 42 24](https://cloud.githubusercontent.com/assets/4352715/8267070/38ac57b4-1752-11e5-9645-1ffe093c4214.png)

Do you have any idea ?
