### ISSUE TITLE
Is PNG Support still working?

### ISSUE THREAD

**Issue by vorg** [spite/ccapture.js#30]
When downloading the file i get `project.tar` than unpacks to `project.tar.cpgz` with nothing inside. Longer movies have 0 bytes or fail completely. JPG export works fine.

OSX 10.12, Chrome 53

**Comment by spite** [comment]
Yes, it should work. I've just tried it, no issues. OSX 10.12, Chrome 53. Have you tried the sample page? https://www.clicktorelease.com/code/conway3d_ccapture
