### ISSUE TITLE
Is there a way to improve performance?

### ISSUE THREAD

**Issue by aleen42** [spite/ccapture.js#33]
As the title say, is there any way to improve the performance when capture to save a video of canvas?

**Comment by spite** [comment]
Depends on what frame encoder you're using, and what part of the process you'd like improved.

If you don't want to lose frames, it has to be a bit slower -or a lot slower- to make sure everything is done before continuing to the next frame. If you don't mind dropping frames or you have a fast enough machine, you could try the webm-mediarecorder format.

**Comment by aleen42** [comment]
@spite Thank you, maybe dropping frames is a good choice.
