### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by zuspan** [spite/ccapture.js#35]
I'm getting this error when i try bower install:
`Unexpected token ]`

I think the bower file might need a comma removed after the author. From this:

`"authors": [
    "Jaume Sanchez <the.spite@gmail.com> (https://www.clicktorelease.com)",
  ],`

to this:

`"authors": [
    "Jaume Sanchez <the.spite@gmail.com> (https://www.clicktorelease.com)"
  ],`

**Comment by spite** [comment]
Ha! Either this has changed recently, or you are the first person _in years_ to use bower to install ccapture (or to do it and report the error).

I've fixed the file (which seems to work) and added an "ignore" part to the bower.json file to skip the bulky examples and assets folders (which doesn't seem to work).

I don't really support bower, that' something someone asked for a long time ago. I'd recommend using npm.

**Comment by zuspan** [comment]
@spite - thanks! Will check i this weekend and will try to switch to npm. Bower is great though! you should support it! haha. thanks again...
