### ISSUE TITLE
GIF is not defined()

### ISSUE THREAD

**Issue by jrogozen** [spite/ccapture.js#36]
Hi,

I installed using npm and am creating a new capture like this

```
var capturer = new CCapture({
                        framerate: 60,
                        format: 'gif',
                        workersPath: './node_modules/ccapture.js/src/',
                        verbose: true
                    });
```

i get an error that GIF is not defined so i'm assuming that i'm not settings the workersPath correctly. I've also tried / and js/

**Comment by spite** [comment]
If you have included CCapturer.all.min.js, or CCapturer.min.js and gif.js, and the workersPath points to where gif.worker.js is, it should work.

**Comment by jrogozen** [comment]
ah thanks. I added ccapture.all.min.js as a script tag and it worked

**Comment by aferriss** [comment]
Just to chime in here, this isn't really a solved issue in the sense that if you want to use CCapture with npm you have to manually include the script tag before your bundle as @jrogozen indicates.

If you include CCapture as
var CCapture = require('ccapture.js');
and want to use the gif mode, CCapture will start to look for a GIF class but come up empty handed. 
To fix this properly, I think you need to rebundle CCapture and define all the extra modules at the top as requires. On top of that it looks like[ gif.js was never intended to be used as a npm module](https://github.com/jnordberg/gif.js/issues/48), so some work would have to be done on that end as well.

**Comment by aceslowman** [comment]
@aferriss I'm running into the same issue currently, has anyone managed to get a working example in npm? Particularly with Webpack? GIF is not defined when using CCapture.min.js, and there are several other modules that can't be found within the CCapture.all.min.js.

```
ERROR in ./node_modules/ccapture.js/build/CCapture.all.min.js
Module not found: Error: Can't resolve './ArrayBufferDataStream' in '/Users/austin/code/THREEJS/threejs_node/node_modules/ccapture.js/build'
 @ ./node_modules/ccapture.js/build/CCapture.all.min.js 1:10753-10787
 @ ./public/js/main.js

ERROR in ./node_modules/ccapture.js/build/CCapture.all.min.js
Module not found: Error: Can't resolve './BlobBuffer' in '/Users/austin/code/THREEJS/threejs_node/node_modules/ccapture.js/build'
 @ ./node_modules/ccapture.js/build/CCapture.all.min.js 1:10788-10811
 @ ./public/js/main.js
```

**Comment by spite** [comment]
Redirected to https://github.com/spite/ccapture.js/issues/78
