### ISSUE TITLE
canvas has been tainted by cross-origin data

### ISSUE THREAD

**Issue by idomadhukar** [spite/ccapture.js#38]
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

The images does show while running my canvas but when i try to capture the canvas i get this issue.
FYI. i tried to capture gif of the canvas.

Do you have any solution about it?
I tried image.crossOrigin = 'anonymous';

**Comment by spite** [comment]
Can you provide an online example of the error? It'll help figure out what's going on
