### ISSUE TITLE
Everything Desaturated? 

### ISSUE THREAD

**Issue by rankinstudio** [spite/ccapture.js#44]
I think this is more related to the canvas in three.js, but when I save images or video out using this awesome module, they all come out desaturated? Is there an easy way to get the colors to look right when you save an image or animation? 

Thanks!

**Comment by spite** [comment]
That's weird, you should be getting exactly what you put, minus the compression depending on the quality. Do all outputs appear desaturated (png, jpg, gif, webm...)?

**Comment by rankinstudio** [comment]
Yes, everything except maybe the gif output. Anything I use to grab the canvas and save out, looks desaturated. I had a different script that was doing the same thing to save jpg and png images out. I ran them through exif viewer online and it said because there were no embedded color profiles that the images may not look right. I figured that may be the issue but the animations you guys show on the preview for the module look great. I have no idea why it would be desaturated. 

Here is my basic setup for grabbing webm with ccapture: 
   var capturer = new CCapture( {
            framerate: 25,
            verbose: true,
            display: true,
            //timeLimit: 10,
            format: 'webm',
            workersPath: '/',
            quality: 50,
            name: 'OrbitVid',
            motionBlurFrames: 0   
   } );

    function animate() {          
            requestAnimationFrame(animate);
            render();
    }       

    function render() {
            renderer.render( scene, camera );
            renderer.render( sceneOrtho, cameraOrtho );
            capturer.capture( renderer.domElement );
    }

    function startRec(){
        capturer.start();
    }
    
    function stopRec(){
        capturer.stop();
        capturer.save();
    }

**Comment by spite** [comment]
I don't have reports about this, and don't know where to start looking. If you're willing to share some code that can reproduce the issue, i'll take a look.

**Comment by rankinstudio** [comment]
Here is a quick example of the issue

http://rankinstudio.com/asteroids/test.html

**Comment by spite** [comment]
I've tried it and it looks like gif, png and jpg give the right result and webm does the desaturated thing -regardless of compression. I'm thinking there's either an issue with the webm encoder, or that webm can't deal with thin lines on top of black background…

**Comment by rankinstudio** [comment]
1. Could you show me the code you used to save out the jpg / png? I keep getting invalid archive messages from winrar. 

2. That is only true until you upload the images to the web, they then desaturate the same as webm. This must be an issue with no color profiles being attached to the canvas? 

Thanks!

**Comment by spite** [comment]
1. I'm just putting a breakpoint on your code after the capturer object is created (L34), and creating a new one in the console with your same syntax, just changing the format. I'm also not using winrar, but keka for osx. Here's my output (expanded the .tar and recompressed as .zip)
[Archive.zip](https://github.com/spite/ccapture.js/files/768895/Archive.zip)

2. That's interesting. Do you know if a color profile can be specified somewhere in the chain, from canvas to file?

**Comment by rankinstudio** [comment]
Thanks!

I have no idea about the color profile. I can't seem to find any documentation regarding color profiles in webgl or three.js.

**Comment by spite** [comment]
Me neither. I've found this http://stackoverflow.com/questions/26500194/html5-canvas-image-discoloration

**Comment by rankinstudio** [comment]
Seems like the solution would be a color profile somehow attached the renderer.domElement.

**Comment by spencerthayer** [comment]
@spite or @rankinstudio was this issue every resolved with CCapture? My webm files are very desaturated.
