### ISSUE TITLE
Running ccapture.js headless?

### ISSUE THREAD

**Issue by Taapo** [spite/ccapture.js#46]
Does anyone know how to run ccapture.js headless - without opening a browser window? I'd love to use this on a server, but there are limits on what can be done.

If someone could shed some experience or light on this - much appreciated!

**Comment by spite** [comment]
I haven't tried anything of the sort. Technically ccapture takes a canvas, so as long as you can produce one -or equivalent-, you should be good. For 2d canvas ,there's a few node modules, and for 3d, i've heard good things about headless-gl. If you can check those out for your case and report the results, I'm open to modify whatever is needed to get it working!

**Comment by cblavier** [comment]
Did anyone managed to run it headless?
I tried to run it with phantom.js but I have issues when capturing frames :
- my socket to ffmpegserver.js is disconnected at the very beginning
- if I use png + tar, Tar.append fails with an empty input

**Comment by spite** [comment]
If you can set up a repo with an example using phantom.js, i will take a look. Thanks!

**Comment by cblavier** [comment]
Thanks, preparing it right now!

**Comment by cblavier** [comment]
Here it is: https://github.com/cblavier/ccapture_headless

**Comment by fisch0920** [comment]
For anyone trying to use headless chrome with this project, note that currently headless chrome doesn't support file downloads ([issue](https://bugs.chromium.org/p/chromium/issues/detail?id=696481)).

**Comment by spite** [comment]
@fisch0920 I guess that's for the new chrome headless, not for phantom.js? does the rest work on chrome headless?

**Comment by fisch0920** [comment]
@spite yes, this is related to the newer [chrome headless](https://developers.google.com/web/updates/2017/04/headless-chrome), not phantom.js.  Note that the rest works fine on chrome headless as far as I can tell, you just need to do some extra work to transfer the captured results to your server for processing as opposed to downloading it directly.  I'm using websockets to accomplish this.

**Comment by fisch0920** [comment]
Also @spite, I've generally loved using this project -- thank you so much for your excellent work!!
