### ISSUE TITLE
Less Nauseating Game of Life 3D Settings for First Example

### ISSUE THREAD

**Issue by drgrib** [spite/ccapture.js#51]
Seriously, I can see this affecting your adoption rates. The Game of Life 3D example *eventually* chills out and is less nauseating. But I can tell you that, as a new user struggling to get the settings right and not yet knowing how to change what I'm recording, I'm getting nauseous every time I try to learn your software.

That's not a state of mind that you want new people experiencing on top of the necessary stress involved in learning a new system. I highly suggest you fast forward the example to a more chill state within Game of Life 3D. You can include the frantic state to demonstrate slow motion and blur effects in a second or third example file.

**Comment by spite** [comment]
Fixed in https://github.com/spite/ccapture.js/commit/1a11d17968c57a7f061219b53f703519288b01c2
