### ISSUE TITLE
gif framedelay control

### ISSUE THREAD

**Issue by alvarobyrne** [spite/ccapture.js#54]
Hello
I wish one could control frame delays in some way when exporting to gif. Something like:
```{frames:{1:200,10:200, 20:200, 30:300}}```
I don't know something like that.
Those frames, 1,10,20 and 30 would have those delays and the rest, would have the default delay.
Thanks.

**Comment by spite** [comment]
I think that belongs more into a proper GIF creation tool. I would advise to use a raw output (PNG or JPG Frame Encoder) and build the desired GIF in said tool.

**Comment by alvarobyrne** [comment]
Ok, thank you.
