### ISSUE TITLE
this.quality is always "undefined" for CCWebMEncoder

### ISSUE THREAD

**Issue by mityok69** [spite/ccapture.js#56]
the quality parameter passed in settings is ignored and not assigned, to this.quality.
so webm is always encoded with the default quality, no matter the passed value

**Comment by spite** [comment]
Good catch!

**Comment by spite** [comment]
Fixed in https://github.com/spite/ccapture.js/commit/d4a661e27ee50867e24989a00259ed7e792e4f8a

I will update npm later today
