### ISSUE TITLE
Black animated gif

### ISSUE THREAD

**Issue by joelnz** [spite/ccapture.js#59]
I'm trying to export an animated GIF from an a-frame scene.
But in the downloaded gif file every frame is black.

my code:

`$('#start').click(function(){
  $('canvas').attr('id','bit');
var canvas = document.getElementById('bit');
var capturer = new CCapture( { 
  format: 'gif', 
  workersPath: 'capture/src/',
  framerate: 30,
  verbose: true,
  name:'file',
  timeLimit: 2,
});
capturer.start();
function render(){
  requestAnimationFrame(render);
  capturer.capture(canvas);
}
render();
})`

**Comment by spite** [comment]
Just in case, make sure the canvas has preserveDrawingBuffer enabled.

**Comment by joelnz** [comment]
I ended up using a-frame's built in screenshot feature within a setInterval function, then used gif.js to combine the generated pngs into an animated gif, then converted the blob to dataURI and used AJAX to upload the gifs to server.

**Comment by GoChartingAdmin** [comment]
@joelnz Would you mind sharing that code with us
