### ISSUE TITLE
Output some error in ios11 safari11?

### ISSUE THREAD

**Issue by hilxm** [spite/ccapture.js#68]
can't capture a video/webm format.. or more errors in safari11.
it seems that it will use the "image/png" for default , not the "image/jpeg".
so the code in line No.401 "t.slice(23)"  is wrong....

**Comment by spite** [comment]
Safari (or any other browser other than Chrome) doesn´t support WebM, so you´re left with the other encoders as option. if the proposed format is not supported by canvas.toDataURL, you'll get image/png as a return value.
