### ISSUE TITLE
Gif Recording

### ISSUE THREAD

**Issue by mokargas** [spite/ccapture.js#7]
Is it possible to record a fixed length of time? Say 1 second, on a button click?

I've tried to do the following with the Gif renderer. I'm using a Canvas object previously created via p5.js:

```javascript
function setup() {
    // setup camera capture
    videoInput = createCapture();
    videoInput.size(canvasWidth, canvasHeight);
    videoInput.position(0, 0);
    videoInput.parent('wrapper');

     // setup canvas
    cnv = createCanvas(canvasWidth, canvasHeight);
    cnv.position(0, 0);
    cnv.parent('wrapper');
}
```

With canvas rendering done in the draw function:

```javascript
function draw() {
    clear();
    // a bunch of drawing calls go here ..
    render();      
 }
        
function render(){
    capturer.capture( cnv.elt );
 }
```

Then in my button handler:
```javascript
 capturer.start();
 setTimeout(function(){
     capturer.stop();
     capturer.save( function( e ) { 
            console.log(e);
           //$('#gifOutput').attr('src', url);
         } );
  }, 1000);
```

I get an exception (which hangs the browser), from gif.coffee on line 72: "Width and height must be set prior to rendering".

**Comment by spite** [comment]
I think there's a couple of issue with trying to do this.

Do you have a jsfiddle or jsbin that I can check to make sure and reply?

**Comment by Yugloocamai** [comment]
I have the exact same issue.

**Comment by spite** [comment]
There's a setting to specify the duration in seconds, timeLimit
