### ISSUE TITLE
gif capture result contains complete black frames

### ISSUE THREAD

**Issue by oliveRudoll** [spite/ccapture.js#71]
hello!

gif capture result contains complete black frames.
do you have a clue / idea why that happens? i guess any hint could help me
find the cause.  i'm using a unity3d webgl build.

![9fc4f017-ceab-f92f-b5a6-b2c0deb4aee4](https://user-images.githubusercontent.com/3080800/35476862-fe2265b6-03b7-11e8-9340-37bc62b2f4ef.gif)

**Comment by oliveRudoll** [comment]
it also seems that first after start captureing the framerate drops really low like 10fps and the goes up to 80fps @greggman @spite can you give me a hint?

**Comment by spite** [comment]
Mmmmh... the only think that comes to mind is if the preserveDrawingBuffer flag is not set, so the context may dispose of the rendered buffer before it's handled by CCapture...

**Comment by oliveRudoll** [comment]
hey spite! thanks for your fast reply!

your hint leeds me to this: 
https://forum.unity.com/threads/webgl-print-canvas.377045/

unity has a method to wait for a frame to be rendered. you can make calls to jscript from c#
they recommend to call the print/capture function from unity after the frame is rendered rather than set preserveDrawingBuffer for performance reasons. (finding the createContext function in the code the unity creates didn't look so easy too)

my question is:
i'm not very aware of how cccapture works though. is "ccapture.capture(canvas);" called every frame?
or what function would be the best entrypoint?

**Comment by spite** [comment]
Yes, preserveDrawinfBuffer can hit performance. If Unity has its own lock/sync mechanism, you should use it. You have to call capturer.capture(canvas) every time you want to push a frame to the capture; so ideally, once every frame, after you're done rendering. May be Unity is more asynchronous than other engines and you're trying to capture before the frame is rendered?

**Comment by oliveRudoll** [comment]
thank you i was able to solve it with your help!

**Comment by spite** [comment]
Glad to hear! Would you mind writing the solution here, for future reference?

**Comment by oliveRudoll** [comment]
it's quite simple: the solution was to wait for endofframe in a unity coroutine before the external call of the js capture function. :-)

unfortunately the gif library is quite too slow for my needs.
