### ISSUE TITLE
Console error when calling capturer.stop()

### ISSUE THREAD

**Issue by rockcs1992** [spite/ccapture.js#75]
Hi,
First I want to say thank you for your effort building this useful library!
I'm using ccapture.all.min.js to record my canvas animation. Everything works fine except for the last step. When I'm calling capturer.stop(), I see an error in the browser and I believe it's preventing me from downloading the video. Any ideas? BTW my canvas size doesn't change at all throughout the process.

![screen shot 2018-02-25 at 9 48 10 pm](https://user-images.githubusercontent.com/16792420/36651213-9f224aac-1a75-11e8-9245-ceb57895bdc4.png)

Below is my code for drawing:
```
function draw {
  background(19,19,19, 200);
  var waveform = fft.analyze(64);
  var w = width;
  var h = height;
  noStroke();

  for (var i = 0; i <= 32; i++) {
    var x = map(i, 0, 32, w / 5, w/5 * 4);
    var y = map(waveform[i+12], 0, 255, h / 4 * 3, h/4);
    circles[i].x = x;
    circles[i].y = y;
    circles[i].show();
  }
  for (var n = 0; n <= 32; n++) {
    if (n < 32) {
      lines[n].x = circles[n].x;
      lines[n].y = circles[n].y;
      lines[n].x2 = circles[n+1].x
      lines[n].y2 = circles[n+1].y
      lines[n].show(200,200,200,100);
    }
    lines[n+32].show(100,100,100,80);
  }
  capturer.capture(document.getElementById('defaultCanvas0'));
}
```

**Comment by spite** [comment]
That error means the canvas has changed size during capture (frames have to be the same size to be converted to video, I assume you're using the WebM capturer). It looks like you're setting the size after capture has started (it says the second frame is different). Make sure the size is set for good before starting capture (before the first .capture)

**Comment by rockcs1992** [comment]
@spite Thanks for the reply. I don't think I'm setting the size after the capture. The `width` and `height` variable in my code is a constant that comes with P5. I observed the size of the canvas throughout the recording process, I'm sure the size doesn't change. BTW I sometimes get the error "Frame 2 has a different size" and sometimes "Frame 3 has a different size".

I kind of wonder what exactly is the 'size' you are referencing to? Is that the size of the canvas? Or it's the size of the content that is animating inside the canvas?

**Comment by spite** [comment]
That message is from Whammy.js, the library to create WebM (https://github.com/spite/ccapture.js/blob/5c794f8fb6aecd909868147cd05b37ee02b4fcbc/src/Whammy.js#L237). You can see in the link how it checks for frame sizes. That message you're seeing is usually because the canvas has changed sizes. Try doing a console.log of the canvas width and height just before passing it to .capture and see if they're constant.

**Comment by rockcs1992** [comment]
I just checked my code, and logged the size of both canvas and each frame. It turns out that the `frame` here is not the size of the canvas. My canvas size stays the same throughout the recording process whereas the size of each frame does differ from each other. So I guess I need to modify my code for animation. I will let you know once I solved this problem.

**Comment by Carlovan** [comment]
Had the same problem, but using the files in the `src/` folder solved it... maybe you need to rebuild everything.

**Comment by spite** [comment]
Possibly related: https://github.com/spite/ccapture.js/issues/76

**Comment by spite** [comment]
Possibly fixed with https://github.com/spite/ccapture.js/commit/a6cafcc8371055cb0344c06999cb588063003037
