### ISSUE TITLE
Capture draw canvas

### ISSUE THREAD

**Issue by luckyboy07** [spite/ccapture.js#76]
i have codepen here please give me some suggestion what's wrong with this or lacking in my code. it captured none. thanks in advance...
[https://codepen.io/luckyboy07/pen/VXpyQw](url)

**Comment by spite** [comment]
Try using the latest build version from the library https://github.com/spite/ccapture.js/tree/master/build, and setting a solid background to the canvas, changing: 
```
context.fillRect(0, 0, canvas.width, canvas.height);
```
with 
```
context.fillStyle = '#fff';
context.fillRect(0, 0, canvas.width, canvas.height);
```

With those changes I've been able to capture your animation.

[sample.webm.zip](https://github.com/spite/ccapture.js/files/1832646/sample.webm.zip)

**Comment by spite** [comment]
There was a side effect on minifying Whammy (the third part library that creates the webm file), I've disabled the minifying for that file. Canvas should still be solid and not transparent. The repo and npm package is updated, let me know if that solved your issue.

**Comment by luckyboy07** [comment]
Thanks a lot!! i follow your advice.. and it captured my canvas..
