### ISSUE TITLE
Resolution Independence - possible ?

### ISSUE THREAD

**Issue by joeblew99** [spite/ccapture.js#8]
I would like to record frames or video, for a canvas bigger than the screen resolution of my laptop.

Was wondering if you had thought about this. I am thinking that dong it server side is the only way.
Basically a way to call webkit on the server, a bit like phantomjs does.

**Comment by edankwan** [comment]
You can always make the canvas bigger than your screen and use CSS to downscale it

**Comment by spite** [comment]
It's up to the developer to set the canvas size that fits better the export. The library doesn't manipulate the source canvas in any way.
