### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by ardcore** [spite/ccapture.js#9]
Hi,
Have you thought about releasing ccapture on npm? It would make it much easier to include it in modern projects.

**Comment by spite** [comment]
Sure, i'll take a look!

**Comment by thejmazz** [comment]
+1. I'm starting a little [threejs-starter-pack](https://github.com/thejmazz/threejs-starter-pack), would be nice to bring in ccapture through npm as opposed to "downloading and saving a js file" :p which works totally fine, but with npm will be easier to stay up to date, is more automated, etc.

**Comment by spite** [comment]
Any idea how to do this? I can add CCapture.js to npm, but the dependencies to Whammy.js for WebM encoding, or gif.js for GIF creation, etc I don't really know how to solve. Especially the gif-worker.js part, since that file has to be loaded by the web worker.

**Comment by thejmazz** [comment]
Some of those are already on npm:
- [Whammy](https://www.npmjs.com/package/whammy)
- [gif.js](https://www.npmjs.com/package/gif.js)
- [tar-js](https://www.npmjs.com/package/tar-js) (this looks different from yours - you write your own?)
- [downloadjs](https://www.npmjs.com/package/downloadjs) (this is on v4.x you have 3.x)

If you refactor to get those dependencies from `npm install x` and then `var x = require('x')`, and you will then need some sort of bundler, and the dist you produce works, then I think that is enough for it to work.

I'm not sure how to work with web workers from npm packages, but I think for now, it's OK to assume those people pulling in ccapture through will be using a build manager, probably webpack or browserify+gulp. Personally, I'd probably use the webpack-copy-plugin and just copy anything required from `node_modules/gif.js/dist/gif.worker.js` to `/dist/js` for example.

Why don't you publish just `CCapture.js` for now? You can also push more micro updates, and it can be tagged as "pre-release" as well. I can try setting it up from my side by bringing in all those other dependencies myself manually through npm. Then we can go from there?

**Comment by spite** [comment]
Published the bundled library (except the gif.js worker script) to https://www.npmjs.com/package/ccapture.js - Please let me know if it works as expected or there are any issues.
